plugins:
  - jekyll-relative-links
theme: jekyll-theme-midnight
relative_links:
  enabled: true
  collections: true
include:
  - README.md 
title: Code candy can
description: Pieces of code I don’t want to lose