title: Code candy can
description: Pieces of code I don’t want to lose

baseurl: "/jekyll-blog-example"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tagplugins:
  - jekyll-relative-links

collections:
  - contributors

paginate: 10

theme: jekyll-theme-midnight

relative_links:
  enabled: true
  collections: true
